spring:
  application:
    name: cloud
  datasource:
    url: jdbc:postgresql://localhost:5432/look_resource
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8899
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
cloud:
  secretId: AKIDiMmxtaEEAqKY6TlZGjxyoPmvqWxEi9k5
  secretKey: JOJyPcZJsFOIwNcdP0PeeVBfvwjPt8Ax
  region: ap-guangzhou
  appId: 1252933270